### ISSUE TITLE
Question: What did you use to make the keymap diagram in the readme?

### ISSUE THREAD

**Issue by mybuddymichael** [duckyb/zmk-sweep#1]
What it says in the title! I'm curious if that was created by a certain keymap program or by hand?

**Comment by duckyb** [comment]
I created it manually using draw.io

**Comment by mybuddymichael** [comment]
Nice! And bummer! Haha, I was hoping that there was a cool keymap visualization tool that I was missing. Thanks for sharing your keymap!
