### ISSUE TITLE
Question: How do you do a Ctrl-Shft-f?

### ISSUE THREAD

**Issue by FearlessSpiff** [duckyb/zmk-sweep#4]
I don't get how you exit the FNC Layer?

Thanks and impressive video btw!

**Comment by duckyb** [comment]
[sweep-web.webm](https://user-images.githubusercontent.com/27895007/200969380-c7e03422-8779-4f88-af6f-529ceb947ddf.webm)

This is how I press `CTRL + SHIFT+ F`
Explanation:
1) enter `FNC` layer
2) press `CTRL + SHIFT`
3) release `FNC` layer key
3) press `F`

> I don't get how you exit the FNC Layer?

Simply by letting go of the layer key.
The mods remain active until another key is pressed.

See the [sticky keys reference](https://zmk.dev/docs/behaviors/sticky-key)

**Comment by FearlessSpiff** [comment]
Wow. Thanks. Have to try the stickies too!
